/*
==================================================================================
DDL Script: Create  tables in Bronze layer
===================================================================================
Script Purpose:
  This script creates table in the 'bronze' Schema, dropping existing table.
===================================================================================
*/
IF OBJECT_ID ('bronze.crm_cust_info' ,'U') IS NOT NULL
	DROP TABLE bronze.crm_cust_info;
GO

CREATE TABLE bronze.crm_cust_info (
	cst_id				INT,
	cst_key				NVARCHAR (50),
	cst_firstname		NVARCHAR (50),
	cst_lastname		NVARCHAR (50),
	cst_marital_status	NVARCHAR (50),
	cst_gndr			NVARCHAR (50),
	cst_create_date		DATE
);
GO

IF OBJECT_ID ('bronze.crm_prod_info' ,'U') IS NOT NULL
	DROP TABLE bronze.crm_prod_info;
GO
  
CREATE TABLE bronze.crm_prod_info (
	prd_id			INT,
	prd_key			NVARCHAR (50),
	prd_nm			NVARCHAR (50),
	prd_cost		INT,
	prd_line		NVARCHAR (50),	
	prd_start_dt	DATE,
	prd_end_dt		DATE
);
GO
  
IF OBJECT_ID ('bronze.crm_sales_detail' ,'U') IS NOT NULL
	DROP TABLE bronze.crm_sales_detail;
GO
  
CREATE TABLE bronze.crm_sales_detail (
	sls_ord_num		NVARCHAR (50),
	sls_prd_key		NVARCHAR (50),
	sls_cust_id		INT,
	sls_order_dt	INT,
	sls_ship_dt		INT,
	sls_due_dt		INT,
	sls_sales		INT,
	sls_quantity	INT,
	sls_price		INT
);
GO
  
IF OBJECT_ID ('bronze.erp_cust_az12' ,'U') IS NOT NULL
	DROP TABLE bronze.erp_cust_az12;
GO
  
CREATE TABLE bronze.erp_cust_az12 (
	cid		NVARCHAR(50),
	bdate	DATE,
	gen		NVARCHAR(50)
);
GO
  
IF OBJECT_ID ('bronze.erp_cust_loc_a101' ,'U') IS NOT NULL
	DROP TABLE bronze.erp_cust_loc_a101;
GO
  
CREATE TABLE bronze.erp_cust_loc_a101(
	cid		NVARCHAR(50),
	ccntry	NVARCHAR(50)
);
GO
  
IF OBJECT_ID ('bronze.erp_px_cat_g1v2' ,'U') IS NOT NULL
	DROP TABLE bronze.erp_px_cat_g1v2;
GO
  
CREATE TABLE bronze.erp_px_cat_g1v2(
	id			NVARCHAR(50),
	cat			NVARCHAR(50),
	subcat		NVARCHAR(50),
	maintanence	NVARCHAR(50)
);
GO
